### ISSUE TITLE
Build is failing for cel.h

### ISSUE THREAD

**Issue by ppapadeas** [cbassa/sattools#1]
Most build recipes are failing with error:
fatal error: cel.h: No such file or directory

**Comment by ppapadeas** [comment]
I have libwcs 4.25 installed. I see 2.9 is the requirement. 4.25 still provides cel.h though.

**Comment by cbassa** [comment]
Unfortunately wcslib changed after version 2.9 and I have not yet had a chance to update the code to use more recent versions. See my private email for more information.
