### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [cbassa/sattools#9]
I suggest to reuse a higher level build system than [your current make script](https://github.com/cbassa/sattools/blob/aa55d0ebc43e8114530e49795062aa2ec1ac546a/makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by cbassa** [comment]
This is something I intend to implement in the future.

**Comment by AndreiCherniaev** [comment]
good idea! But please use meson or CMake. Forget about old-school Autotools, it was my grand-grandfather used during a break between mammoth hunting
